version: "3"
services:
  gateway:
    build: ./gateway
    environment:
      - IDENTITY_SERVICE=identity_service:5001
    ports:
      - "5000:5000"
  identity_service:
    build: ./identity_service
    environment:
      - PORT=5001
      - HOST=identity_service
      - DB_HOST=mysql
      - SERVICE_DISCOVERY_URL=http://gateway:5000
      - NODE_ENV=development

  order_service:
    build: ./order_service
    environment:
      - PORT=5001
      - HOST=order_service
      - DB_HOST=mysql
      - SERVICE_DISCOVERY_URL=http://gateway:5000
      - NODE_ENV=development

  cart_service:
    build: ./cart_service
    environment:
      - PORT=5001
      - HOST=cart_service
      - DB_HOST=mysql
      - SERVICE_DISCOVERY_URL=http://gateway:5000
      - NODE_ENV=development

  product_service:
    build: ./product_service
    restart: always
    depends_on:
      - mysql
    environment:
      - PORT=5001
      - HOST=product_service
      - DB_HOST=mysql
      - SERVICE_DISCOVERY_URL=http://gateway:5000
      - NODE_ENV=development

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_produit
    ports:
      - "3306:3306"
