import UserRepository from "../User/UserRepository";
import { Roles } from "../entities";

const users = [
  {
    id: 1,
    name: "Yance Leijs",
    email: "yleijs0@themeforest.net",
    gender: "Male",
    phoneNumber: "727-147-0821",
    address: "79 Darwin Street",
    password: "BdPZt89",
  },
  {
    id: 2,
    name: "Emmott Humphris",
    email: "ehumphris1@jigsy.com",
    gender: "Male",
    phoneNumber: "222-514-0492",
    address: "09 Menomonie Junction",
    password: "3PLJ7zroTpCR",
  },
  {
    id: 3,
    name: "Kermy Bywaters",
    email: "kbywaters2@berkeley.edu",
    gender: "Male",
    phoneNumber: "190-429-3174",
    address: "69 Straubel Terrace",
    password: "rpfUOq",
  },
  {
    id: 4,
    name: "Saxon Wheater",
    email: "swheater3@tinyurl.com",
    gender: "Male",
    phoneNumber: "331-247-6418",
    address: "39 Oriole Way",
    password: "esnhKKH3g",
  },
  {
    id: 5,
    name: "Malina Ebourne",
    email: "mebourne4@sitemeter.com",
    gender: "Female",
    phoneNumber: "604-377-0055",
    address: "8 Esch Plaza",
    password: "uwG4x2",
  },
  {
    id: 6,
    name: "Mort Godfroy",
    email: "mgodfroy5@hibu.com",
    gender: "Genderqueer",
    phoneNumber: "390-295-2718",
    address: "80954 Memorial Avenue",
    password: "vDXyGt93HNA8",
  },
  {
    id: 7,
    name: "Goldina Bonder",
    email: "gbonder6@cmu.edu",
    gender: "Agender",
    phoneNumber: "831-278-0623",
    address: "56437 Northfield Parkway",
    password: "3Th8iZ",
  },
  {
    id: 8,
    name: "Umeko Bagg",
    email: "ubagg7@hibu.com",
    gender: "Female",
    phoneNumber: "836-129-9414",
    address: "0582 Vidon Plaza",
    password: "rHxh5e",
  },
  {
    id: 9,
    name: "Giordano Rama",
    email: "grama8@amazon.de",
    gender: "Male",
    phoneNumber: "342-811-1851",
    address: "187 Sage Plaza",
    password: "oIz46IdQs4",
  },
  {
    id: 10,
    name: "Mahalia Lafaye",
    email: "mlafaye9@tripod.com",
    gender: "Female",
    phoneNumber: "648-210-8238",
    address: "95290 Northfield Court",
    password: "fhi33obUEMC",
  },
  {
    id: 11,
    name: "Torey Twelve",
    email: "ttwelvea@vk.com",
    gender: "Female",
    phoneNumber: "413-695-4256",
    address: "72398 Texas Pass",
    password: "Yao5ozPqjL",
  },
  {
    id: 12,
    name: "Berta McJarrow",
    email: "bmcjarrowb@wired.com",
    gender: "Female",
    phoneNumber: "576-639-9096",
    address: "339 Onsgard Avenue",
    password: "tT2uIU7FX3jn",
  },
  {
    id: 13,
    name: "Doralynn Magnar",
    email: "dmagnarc@reference.com",
    gender: "Female",
    phoneNumber: "179-780-2978",
    address: "7 Shelley Hill",
    password: "xdwyFMAsl",
  },
  {
    id: 14,
    name: "Joell Applin",
    email: "japplind@xrea.com",
    gender: "Female",
    phoneNumber: "157-680-3391",
    address: "19867 Melby Hill",
    password: "bb83ooQxZ",
  },
  {
    id: 15,
    name: "Cathrine Smoote",
    email: "csmootee@gravatar.com",
    gender: "Female",
    phoneNumber: "738-217-9450",
    address: "86 Superior Court",
    password: "Y6Wc8el7YHA9",
  },
  {
    id: 16,
    name: "Karoly Eccleston",
    email: "kecclestonf@addtoany.com",
    gender: "Polygender",
    phoneNumber: "619-998-7034",
    address: "3 Warner Plaza",
    password: "HtKKt0R1JG2",
  },
  {
    id: 17,
    name: "Tamiko Borham",
    email: "tborhamg@redcross.org",
    gender: "Female",
    phoneNumber: "520-827-2528",
    address: "63463 Hoffman Trail",
    password: "W3fTtWx0NXqs",
  },
  {
    id: 18,
    name: "Emmey Pizer",
    email: "epizerh@google.com",
    gender: "Female",
    phoneNumber: "335-714-8470",
    address: "780 Orin Junction",
    password: "AZ1y9vXK0c7",
  },
  {
    id: 19,
    name: "Flinn Luddy",
    email: "fluddyi@intel.com",
    gender: "Male",
    phoneNumber: "140-170-5634",
    address: "8 Sundown Pass",
    password: "oAQWes1sBpE",
  },
  {
    id: 20,
    name: "Idette Entwisle",
    email: "ientwislej@latimes.com",
    gender: "Female",
    phoneNumber: "359-660-5562",
    address: "0 Anderson Place",
    password: "Q20obF",
  },
  {
    id: 21,
    name: "Dale Moroney",
    email: "dmoroneyk@woothemes.com",
    gender: "Female",
    phoneNumber: "872-978-0546",
    address: "9393 Norway Maple Point",
    password: "UdWZzFe50",
  },
  {
    id: 22,
    name: "Sephira Di Meo",
    email: "sdil@noaa.gov",
    gender: "Female",
    phoneNumber: "474-567-4697",
    address: "9650 Redwing Terrace",
    password: "ObOa6W61xn",
  },
  {
    id: 23,
    name: "Goober Carlyon",
    email: "gcarlyonm@w3.org",
    gender: "Male",
    phoneNumber: "408-858-3407",
    address: "6 Esker Center",
    password: "9nl1U47vI",
  },
  {
    id: 24,
    name: "Ralina Smieton",
    email: "rsmietonn@biblegateway.com",
    gender: "Female",
    phoneNumber: "332-610-6486",
    address: "28183 Forest Crossing",
    password: "M1IvdL2YmK",
  },
  {
    id: 25,
    name: "Corene Southard",
    email: "csouthardo@miibeian.gov.cn",
    gender: "Female",
    phoneNumber: "813-979-0003",
    address: "91 Melody Trail",
    password: "mXEmGPSnCU",
  },
  {
    id: 26,
    name: "Willi Biaggelli",
    email: "wbiaggellip@mashable.com",
    gender: "Male",
    phoneNumber: "540-805-3504",
    address: "5265 Nobel Junction",
    password: "ND9mDjJmMSh",
  },
  {
    id: 27,
    name: "Nelia Leal",
    email: "nlealq@addtoany.com",
    gender: "Female",
    phoneNumber: "789-225-2888",
    address: "89538 Stang Drive",
    password: "RNNTlwpNZ8F",
  },
  {
    id: 28,
    name: "Nealy Mulvey",
    email: "nmulveyr@storify.com",
    gender: "Male",
    phoneNumber: "690-716-2684",
    address: "08623 Grasskamp Alley",
    password: "cb7Mo2IiZSL",
  },
  {
    id: 29,
    name: "Orel Halvorsen",
    email: "ohalvorsens@nytimes.com",
    gender: "Female",
    phoneNumber: "197-176-8360",
    address: "20073 Carioca Alley",
    password: "vx8sKhSk",
  },
  {
    id: 30,
    name: "Anabelle Emson",
    email: "aemsont@opensource.org",
    gender: "Female",
    phoneNumber: "804-663-8359",
    address: "67584 Green Avenue",
    password: "kiNlOYF",
  },
];

export default function faker(repo: UserRepository) {
  repo.createUser(
    "yasmine",
    "email@example.com",
    "Password1",
    "",
    "",
    "",
    Roles.Admin
  );
  users.forEach((i) =>
    repo.createUser(
      i.name,
      i.email,
      i.password,
      i.gender,
      i.phoneNumber,
      i.address
    )
  );
}
